#include "tram_odometry/navigation.hpp"
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <stdexcept>

namespace {
void require(bool pass,const char* message) {if(!pass) throw std::runtime_error(message);}
}
int main() {
  using namespace tram_odometry;
  const auto path=std::filesystem::temp_directory_path()/"tram_body_heading_circle.csv";
  // Body midpoint follows a circle. Master is 6.098 m behind that midpoint:
  // 9.873 m behind front bogie, whose distance from midpoint is 7.55/2 m.
  // This is independent rigid-body geometry, not generated by RouteMap.
  constexpr double radius=25., behind=9.873-7.55/2., forward=9.873;
  const double master_radius=std::hypot(radius,behind);
  std::ofstream file(path);file<<"direction,s,x,y,z\n"<<std::setprecision(17);
  for(int i=0;i<=1600;++i) {
    const double angle=i*.002;
    file<<"out,"<<master_radius*angle<<','
        <<radius*std::cos(angle)+behind*std::sin(angle)<<','
        <<radius*std::sin(angle)-behind*std::cos(angle)<<",3\n";
  }
  file.close();
  for(double angle:{.3,1.2,2.7}) {
    const Point3 master{radius*std::cos(angle)+behind*std::sin(angle),
                        radius*std::sin(angle)-behind*std::cos(angle),3};
    const Point3 body{-std::sin(angle),std::cos(angle),0};
    const Point3 expected=master+body*forward+Point3{0,0,-3};
    NavigationConfig c;c.map_file=path.string();c.output_projection="enu";
    c.route_direction="out";c.use_startup_gnss=false;c.use_map_without_gnss=true;
    c.start_s_m=master_radius*angle;
    Navigation nav(EstimatorConfig{},c);
    nav.submitVehicle('F',0,100.);
    nav.submitVehicle('C',0,100.1);
    const auto r=nav.output();
    const double error=std::hypot(r.position.x-expected.x,r.position.y-expected.y);
    std::cout<<"body offset error "<<error<<" m\n";
    require(r.mapped&&r.position_valid,"configured map produces an absolute pose");
    require(error<.06,"master trajectory tangent is not the rigid body heading on a turn");
    require(std::abs(r.position.z)<1e-9,"antenna height applies once");
    for(bool rover:{false,true}) {
      auto anchored=c;anchored.use_startup_gnss=true;anchored.use_map_without_gnss=false;
      anchored.rover_fallback_delay_s=0;anchored.anchor_residual_decay_m=0;
      Navigation with_fix(EstimatorConfig{},anchored);
      geo::EnuDatum datum({c.map_datum_lat_deg,c.map_datum_lon_deg,c.map_datum_alt_m});
      const auto antenna=master+body*(rover?12.436:0.);
      const auto llh=datum.fromEnu({antenna.x,antenna.y,antenna.z});
      for(int i=0;i<3;++i) {
        const double time=100.+.1*i;
        with_fix.submitVehicle('F',0,time);
        with_fix.submitFix(rover,llh.latitude_deg,llh.longitude_deg,llh.height_m,2,time);
        with_fix.submitVehicle('C',0,time+.001);
      }
      const auto q=with_fix.output();
      require(q.anchored,"either antenna initializes a curved route");
      require(std::hypot(q.position.x-expected.x,q.position.y-expected.y)<.08,
              "rover matching and base_link use the same rigid body orientation");
    }
  }
  RouteMap map;require(map.load(path.string()),"load endpoint fixture");
  for(double coordinate:{-100.,0.,1000.}) {
    const auto u=map.bodyDirection("out",coordinate,6.098);
    require(std::isfinite(u.x+u.y+u.z)&&std::abs(std::hypot(u.x,u.y)-1)<1e-9,
            "body heading remains finite and normalized at clamped endpoints");
  }
  for(double invalid:{-1.,21.,std::numeric_limits<double>::quiet_NaN()}) {
    NavigationConfig c;c.body_heading_lookahead_m=invalid;bool rejected=false;
    try {Navigation n(EstimatorConfig{},c);} catch(const std::invalid_argument&) {rejected=true;}
    require(rejected,"invalid heading geometry is rejected");
  }
  std::filesystem::remove(path);
  return 0;
}
